### ISSUE TITLE
load-path

### ISSUE THREAD

**Issue by maacl** [panicz/pamphlet#2]
Cf bottom p. 19 it is not the main repo dir but the `/libraries` dir that needs to be placed in the load-path.

**Comment by panicz** [comment]
Thanks for noticing. I added some more information. Do you think it is sufficient now?

To be honest, I don't want to put too much technical detail there -- I believe that it would be best if the Guile module system got improved so that the lacking modules could be downloaded and installed automatically upon the (use-modules ...) invocation. (I think that R is actually better in this regard than Guile)

**Comment by maacl** [comment]
Yes, that looks fine.

And I agree, a package manager useable from the REPL would be great.

**Comment by panicz** [comment]
Maybe I'll talk to the Guile guys about it (I think I could implement that, but I think that there are some issues that need to be well thought.)
In the meantime, I'm closing this issue. Thanks again!
