### ISSUE TITLE
[suggestions] propositional logic

### ISSUE THREAD

**Issue by drcz** [panicz/pamphlet#6]
page 21:
_"The semantics of the language is as follows: atomic formulas can either
be true or false, depending on a given valuation. The compound formula
is true if it is a negation and the negated sub-formula is false, or if it is a
conjunction and all its sub-formulas are true, or if it is a disjunction and at
least one of its sub-formulas is true; otherwise, the formula is false."_
1) it is not stated explicitly that the _atomic formulas_ are _propositional variables_ mentioned in previous paragraph (maybe it's not that obvious?),
2) also in previous paragraph formulas were at first called _expressions_, maybe unnecessarily?
3) in this definition it's not that clearly stated that the semantics is a function of valuations, and perhaps the definition _"A valuation is a mapping between the names of atomic formulas and
their logical values."_ should appear earlier?
or at least the reader could be assured that things will get explained in more details below... or not?

i will propose something more concrete tomorrow...
(since there's the name of Tarski on this page, these are no longer trifles!)

**Comment by panicz** [comment]
ad. 1: i agree -- it would be better if it was expressed explicitly
ad. 2: i think that in this context using 'formulas' and 'expressions'
interchangably isn't harmful. i think that post presentations of
propositional logic begin with their semantic side rather than syntactic,
and that's why they prefer the term 'formula'
ad. 3: maybe i should rather add to the preface that the presentation isn't
always incremental, and sometimes if something isn't clear, one should try
to read until the end of current section/chapter. i think that the same
problem appears earlier, when cons is used for the first time

**Comment by drcz** [comment]
i tried to reorganize this part of the text a bit, but can't say i'm satisfied... maybe it's unnecessary?
pushed to derczykowy. perhaps you could polish it? 

ad 3 yes

ps did I mention you've got very strange finger?

**Comment by panicz** [comment]
well yes, my finger is very strange indeed.

I tried to rephrase the explanation once again, impertinent enough to do that on your branch.
If you find it satisfactory, then you can merge the branch to master (but remember to regenerate the pdf file using pdflatex and move it to the main directory before commiting and pushing).

Otherwise keep on complaining.

**Comment by drcz** [comment]
love it!
i have trouble regenerating the document, it looks uglier than yours; probably I have older version of texlivesomething and my debian flavour is long dead and not all repos are there and... 
briefly: because of the thing called _learned helplesness_ you have to merge and regenerate the thing on your own, sorry!

no doubt something about this finger is incredibly strange.

**Comment by panicz** [comment]
the thingy is merged and regenerated and waits for another remarks of yours
(and the strange finger participated reluctantly in pressing shift at various occasions)

**Comment by drcz** [comment]
nice!
